title = "Anonymous Telegram bot config"

[application]
debug = true
port = 8082

[telegram]
bot_token = ""

[rabbit]
connection_string = "amqp://guest:guest@localhost:5672/"
new_chat_notification_exchange = "chat.notification"
new_message_notification = "msg.notification"

[redis]
host = "localhost"
port = 6379
username = ""
password = ""
db = 5

